from basetypes.a_root import SerializationNode, SerialType, Root

from enum import Enum


class OptimizedDataType(Enum):
    ALIAS = 1  # alias named types to create shortcuts within the type trees for frequently used types

    UINT8 = 2
    UINT16 = 3
    UINT32 = 4
    UINT64 = 5

    NEG_UINT8 = 6
    NEG_UINT16 = 7
    NEG_UINT32 = 8
    NEG_UINT64 = 9

    # shortcut for every base type as within the base type tree, only for serialization related
    NONE = 10
    BOOL = 11
    INT = 12
    FLOAT = 13
    DECIMAL = 14
    STRING = 15
    BYTES = 16

    TYPE = 17
    SPARSE_OBJECT = 18

    DATETIME = 19
    DATE = 20
    TIME = 21
    TIMEDELTA = 22

    STRING_WITH_CONSTRAINT = 23
    BYTES_WITH_CONSTRAINT = 24
    INT_WITH_CONSTRAINT = 25


### BEGIN AUTO GENERATION
# Auto-generated from OptimizedDataType for auto-completion purpose
class OptimizedData(SerializationNode):
    ALIAS = ...
    UINT8 = ...
    UINT16 = ...
    UINT32 = ...
    UINT64 = ...
    NEG_UINT8 = ...
    NEG_UINT16 = ...
    NEG_UINT32 = ...
    NEG_UINT64 = ...
    NONE = ...
    BOOL = ...
    INT = ...
    FLOAT = ...
    DECIMAL = ...
    STRING = ...
    BYTES = ...
    TYPE = ...
    SPARSE_OBJECT = ...
    DATETIME = ...
    DATE = ...
    TIME = ...
    TIMEDELTA = ...
    STRING_WITH_CONSTRAINT = ...
    BYTES_WITH_CONSTRAINT = ...
    INT_WITH_CONSTRAINT = ...
### END AUTO GENERATION

    def optimized_path_until(self, enum_val: OptimizedDataType):
        return bytes([enum_val.value])


Optimized: OptimizedData = Root.register_serialization_child(SerialType.Optimized, OptimizedDataType, OptimizedData)


if __name__ == '__main__':
    from basetypes.autocomplete_helper import generate_autocompletion_for_enum
    print(generate_autocompletion_for_enum(OptimizedDataType))
